Repository compio-rs/compio, pull requests merged in 2023-10, with the labels that each got.

#83 Use SetFileCompletionNotificationModes when attaching.
  compio-driver/Cargo.toml
  compio-driver/src/iocp/mod.rs
  compio-driver/src/iocp/op.rs
  compio/tests/file.rs
  compio/tests/runtime.rs
Labels: driver: IOCP

#87 Implement `IoBuf` for `Box<[u8]>`
  compio-buf/src/io_buf.rs
  compio-buf/src/lib.rs
Labels: enhancement

#86 Add a multi-threading dispatcher
  Cargo.toml
  compio-dispatcher/Cargo.toml
  compio-dispatcher/src/lib.rs
  compio-driver/src/iour/mod.rs
  compio-fs/src/file.rs
  compio-fs/src/named_pipe.rs
  compio-net/src/socket.rs
  compio-net/src/tcp.rs
  compio-net/src/udp.rs
  compio-net/src/unix.rs
  compio-runtime/src/attacher.rs
  compio-runtime/src/lib.rs
  compio/Cargo.toml
  compio/examples/dispatcher.rs
  compio/src/lib.rs
  compio/tests/dispatcher.rs
  compio/tests/driver.rs
  compio/tests/runtime.rs
Labels: enhancement

#89 Fix: unable to resolve `compio-runtime` in macros
  compio-macros/src/lib.rs
Labels: bug

#90 Remove cancel queue for io-uring driver.
  compio-driver/src/iour/mod.rs
Labels: driver: io-uring

#94 Add custom `IoSlice`
  compio-buf/Cargo.toml
  compio-buf/src/io_buf.rs
  compio-buf/src/io_slice.rs
  compio-buf/src/lib.rs
  compio-driver/src/iour/op.rs
  compio-driver/src/poll/op.rs
  compio-driver/src/unix/op.rs
Labels: enhancement

#95 Use `compio-macros` in tests
  compio/Cargo.toml
  compio/tests/dispatcher.rs
  compio/tests/event.rs
  compio/tests/file.rs
  compio/tests/runtime.rs
  compio/tests/tcp_accept.rs
  compio/tests/tcp_connect.rs
  compio/tests/udp.rs
  compio/tests/unix_stream.rs
Labels: enhancement

#71 Compio IO crate
  Cargo.toml
  azure-pipelines.yml
  compio-buf/src/buf_result.rs
  compio-buf/src/io_buf.rs
  compio-buf/src/io_slice.rs
  compio-buf/src/iter.rs
  compio-buf/src/lib.rs
  compio-buf/src/slice.rs
  compio-driver/src/iocp/op.rs
  compio-io/Cargo.toml
  compio-io/src/buffer.rs
  compio-io/src/lib.rs
  compio-io/src/read/buf.rs
  compio-io/src/read/ext.rs
  compio-io/src/read/mod.rs
  compio-io/src/util/internal.rs
  compio-io/src/util/mod.rs
  compio-io/src/util/null.rs
  compio-io/src/util/repeat.rs
  compio-io/src/util/take.rs
  compio-io/src/write/buf.rs
  compio-io/src/write/ext.rs
  compio-io/src/write/mod.rs
  compio/Cargo.toml
  compio/tests/io.rs
Labels: enhancement

#96 Add `doc(cfg())` support
  compio-buf/Cargo.toml
  compio-buf/src/lib.rs
  compio-driver/Cargo.toml
  compio-driver/src/iour/mod.rs
  compio-driver/src/lib.rs
  compio-driver/src/op.rs
  compio-driver/src/poll/mod.rs
  compio-fs/Cargo.toml
  compio-fs/src/file.rs
  compio-fs/src/lib.rs
  compio-net/Cargo.toml
  compio-net/src/lib.rs
  compio-net/src/socket.rs
  compio-net/src/tcp.rs
  compio-runtime/Cargo.toml
  compio-runtime/src/attacher.rs
  compio-runtime/src/event/mod.rs
  compio-runtime/src/lib.rs
  compio-signal/Cargo.toml
  compio-signal/src/lib.rs
  compio/Cargo.toml
  compio/benches/named_pipe.rs
  compio/examples/named_pipe.rs
  compio/src/lib.rs
Labels: documentation

#91 Add unix pipe.
  compio-fs/Cargo.toml
  compio-fs/src/lib.rs
  compio-fs/src/pipe.rs
  compio-runtime/Cargo.toml
  compio-runtime/src/event/eventfd.rs
  compio-runtime/src/event/pipe.rs
  compio/Cargo.toml
  compio/examples/named_pipe.rs
Labels: enhancement

#101 Add preadv & pwritev support
  compio-driver/src/iour/op.rs
  compio-driver/src/lib.rs
  compio-driver/src/op.rs
  compio-driver/src/poll/mod.rs
  compio-driver/src/poll/op.rs
  compio-driver/src/unix/op.rs
  compio-fs/src/file.rs
  compio-fs/src/pipe.rs
  compio-io/src/read/ext.rs
  compio-io/src/read/mod.rs
  compio-io/src/write/ext.rs
  compio-io/src/write/mod.rs
  compio-net/src/socket.rs
  compio-net/src/tcp.rs
  compio-net/src/unix.rs
  compio-runtime/src/event/eventfd.rs
  compio-runtime/src/event/pipe.rs
  compio/tests/io.rs
  compio/tests/udp.rs
Labels: enhancement

#106 Async DNS resolve
  compio-driver/Cargo.toml
  compio-driver/src/iocp/mod.rs
  compio-fs/src/file.rs
  compio-net/Cargo.toml
  compio-net/src/lib.rs
  compio-net/src/resolve/glibc.rs
  compio-net/src/resolve/mod.rs
  compio-net/src/resolve/windows.rs
  compio-net/src/tcp.rs
  compio-net/src/udp.rs
  compio-net/src/unix.rs
  compio-runtime/src/event/eventfd.rs
  compio-runtime/src/event/pipe.rs
  compio/benches/net.rs
  compio/examples/dispatcher.rs
  compio/examples/net.rs
  compio/tests/dispatcher.rs
  compio/tests/driver.rs
  compio/tests/runtime.rs
  compio/tests/tcp_accept.rs
  compio/tests/tcp_connect.rs
  compio/tests/udp.rs
Labels: enhancement

#110 feat(driver): fusion driver
  compio-driver/Cargo.toml
  compio-driver/src/fusion/mod.rs
  compio-driver/src/fusion/op.rs
  compio-driver/src/iour/op.rs
  compio-driver/src/lib.rs
  compio-driver/src/op.rs
  compio-driver/src/poll/op.rs
  compio-driver/src/unix/op.rs
Labels: enhancement, driver: fusion

#109 Make schedule Send with panics.
  compio-runtime/src/runtime/mod.rs
Labels: bug

#111 Make DNS resolve async on Unix
  compio-net/Cargo.toml
  compio-net/src/lib.rs
  compio-net/src/resolve/glibc.rs
  compio-net/src/resolve/mod.rs
  compio-net/src/resolve/unix.rs
  compio-net/src/resolve/windows.rs
  compio-net/src/tcp.rs
  compio-net/src/udp.rs
Labels: enhancement, package: net

#116 docs(net): add example for async resolve.
  compio/examples/resolve.rs
Labels: documentation

#114 doc: add `CONTRIBUTION.md`
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#117 Add `develop-guide` in ToC of `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#115 feat(buf): redesign IoBufMut
  compio-buf/src/io_buf.rs
  compio-buf/src/iter.rs
  compio-buf/src/slice.rs
  compio-driver/src/iocp/op.rs
  compio-driver/src/iour/op.rs
  compio-driver/src/poll/op.rs
  compio-io/src/buffer.rs
  compio-io/src/read/ext.rs
  compio-io/src/read/mod.rs
  compio-io/src/util/internal.rs
  compio-io/src/util/repeat.rs
  compio/tests/io.rs
  compio/tests/runtime.rs
Labels: package: buf, package: io, refactor

#118 feat(fs, net): add impl for &T
  compio-fs/src/file.rs
  compio-fs/src/named_pipe.rs
  compio-fs/src/pipe.rs
  compio-net/src/lib.rs
  compio-net/src/resolve/mod.rs
  compio-net/src/socket.rs
  compio-net/src/tcp.rs
  compio-net/src/udp.rs
  compio-net/src/unix.rs
  compio/benches/net.rs
  compio/tests/udp.rs
Labels: enhancement, package: net, package: fs

#119 feat(tls): add native-tls adapters.
  Cargo.toml
  azure-pipelines.yml
  compio-io/src/buffer.rs
  compio-io/src/lib.rs
  compio-io/src/read/buf.rs
  compio-io/src/write/buf.rs
  compio-net/Cargo.toml
  compio-tls/Cargo.toml
  compio-tls/src/adapter.rs
  compio-tls/src/lib.rs
  compio-tls/src/stream.rs
  compio-tls/src/wrapper.rs
Labels: enhancement, package: tls

#122 doc: add contribution section to README.md
  README.md
Labels: documentation

#126 fix: unused imports warnings
  compio-driver/src/iour/mod.rs
  compio-driver/src/poll/mod.rs
  compio-net/src/resolve/glibc.rs
  compio-net/src/resolve/unix.rs
  compio-net/src/resolve/windows.rs
Labels: refactor
